### ISSUE TITLE
KtwDatabaseMenuBundle and SonataAdmin integration, how to properly setup project?

### ISSUE THREAD

**Issue by paquitodev** [kevintweber/KtwDatabaseMenuBundle#10]
I'm working a **Symfony 2.8** project so I started by setting up everything. I am using SonataAdminBundle (dev-master) and it's dependencies: KnpMenuBundle and so on. I'm using this bundle for store menu items at DB.

After get SonataAdmin working I am trying to setup an Admin class for `KtwDatabaseMenuBundle` so I have defined services as follow:

    // Clanmovil\PlatformBundle\Resources\config\services.yml
    services:
        sonata.admin.menuitem:
            class: Clanmovil\PlatformBundle\Controller\Admin\MenuItemAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: "Config", label: "Menu" }
            arguments:
                - ~
                - kevintweber\KtwDatabasemenuBundle\Entity\MenuItem
                - ~
Doctrine is setup as default meaning I didn't change a line there:

    app/config/config.yml
    doctrine:
        dbal:
            driver:   pdo_mysql
            host:     "%database_host%"
            port:     "%database_port%"
            dbname:   "%database_name%"
            user:     "%database_user%"
            password: "%database_password%"
            charset:  UTF8          
    
        orm:
            auto_generate_proxy_classes: "%kernel.debug%"
            naming_strategy: doctrine.orm.naming_strategy.underscore
            auto_mapping: true

Any time I try to create a new element by going to *Add* I got this error:

> Warning: Missing argument 1 for
> kevintweber\KtwDatabaseMenuBundle\Entity\MenuItem::__construct(),
> called in
> /var/www/html/platform-cm/vendor/sonata-project/doctrine-orm-admin-bundle/Model/ModelManager.php
> on line 450 and defined

What I am missing here? What is the right way to handle this?

**Comment by kevintweber** [comment]
Your question is intriguing to me, so I did a bit of research.

The error on line 450 of ModelManager at https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/2.3.3/Model/ModelManager.php#L450 assumes the entity constructor has no parameters.  The problem you'll see is that the MenuItem entity constructor requires two parameters. (https://github.com/kevintweber/KtwDatabaseMenuBundle/blob/master/Entity/MenuItem.php#L105)

I also found this somewhat old issue: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/200

It looks to me like your trying to do something which is not supported by the Sonata project.  I don't know the best way for you to proceed.  I can think of two options:

1. Override the ModelManager with a child class that can inject the menu item name and factory into the builder method.  I don't know how to do this or if it's even feasible.
2. Extend the MenuItem class so that the constructor is takes no parameters.  You would also have to build a factory class that constructs DatabaseMenuFactory objects and unique names using static methods.

I hope this helps.   - Kevin

**Comment by paquitodev** [comment]
@kevintweber can you post an example for point (2)? I am asking how I can do that. I will post this same issue on SonataAdmin side and see if I can get any answer there

**Comment by kevintweber** [comment]
@paquitodev I should warn you first that I do not use the Sonata bundles, so I have no idea if this will fix your issue.  With that in mind, this is what I mean by option 2:

```php
use kevintweber\KtwDatabaseMenuBundle\Menu\DatabaseMenuFactory;

class MenuItemHelper
{
    protected $databaseMenuFactory;

    public function __construct(DatabaseMenuFactory $databaseMenuFactory)
    {
        $this->databaseMenuFactory = $databaseMenuFactory;
    }

    public static function getFactory()
    {
        return self::$databaseMenuFactory;
    }

    public static function getName()
    {
        // Generate a name here.  Either the name could be injected
        // in like the factory above, or you could randomly generate a name...
    }
}
```
Note: Injecting dependencies into classes with static getters can be tricky because now you have to worry about the order of method invocation.  You need to be sure to call the constructor before the getFactory method.  I'm sure a better solution could be found.

```php
use kevintweber\KtwDatabaseMenuBundle\Entity\MenuItem;

class ExtendedMenuItem extends MenuItem
{
    public function __construct()
    {
        parent::__construct(
            MenuItemHelper::getName(),
            MenuItemHelper::getFactory()
        );
    }
}
```

I hope this helps.  -Kevin

**Comment by reypm** [comment]
@kevintweber is there any way to extend your entity and lacks `$name` attribute? Why? Suppose that I am creating a new menu item from scratch why that menu should have a name even before persist to DB? I have change to [EasyAdminBundle][1] which has a way to overwrite it's method and use the `__construct()` from entity as you can see [here][2] but I am not clear at all how I can implement this for your entity, can you give me some help to get it? I am playing with this piece of code:

    public function createNewMenuItemEntity($name, FactoryInterface $factory)
    {
        return new MenuItem($name, $factory);
    }

But I got almost the same error as Sonata due to `$name` see below:

> Warning: Missing argument 1 for kevintweber\KtwDatabaseMenuBundle\Entity\MenuItem::__construct(), called in /var/www/html/platform-cm/vendor/javiereguiluz/easyadmin-bundle/Controller/AdminController.php on line 415 and defined

 [1]: https://github.com/javiereguiluz/EasyAdminBundle
 [2]: https://github.com/javiereguiluz/EasyAdminBundle/blob/master/Resources/doc/tutorials/customizing-admin-controller.md#customize-the-instantiation-of-a-single-entity
